/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FlashCard {
        "answer": string;
        "question": string;
    }
    interface TriviaLoader {
        "gsheeturl": string;
    }
}
declare global {
    interface HTMLFlashCardElement extends Components.FlashCard, HTMLStencilElement {
    }
    var HTMLFlashCardElement: {
        prototype: HTMLFlashCardElement;
        new (): HTMLFlashCardElement;
    };
    interface HTMLTriviaLoaderElement extends Components.TriviaLoader, HTMLStencilElement {
    }
    var HTMLTriviaLoaderElement: {
        prototype: HTMLTriviaLoaderElement;
        new (): HTMLTriviaLoaderElement;
    };
    interface HTMLElementTagNameMap {
        "flash-card": HTMLFlashCardElement;
        "trivia-loader": HTMLTriviaLoaderElement;
    }
}
declare namespace LocalJSX {
    interface FlashCard {
        "answer"?: string;
        "question"?: string;
    }
    interface TriviaLoader {
        "gsheeturl"?: string;
    }
    interface IntrinsicElements {
        "flash-card": FlashCard;
        "trivia-loader": TriviaLoader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "flash-card": LocalJSX.FlashCard & JSXBase.HTMLAttributes<HTMLFlashCardElement>;
            "trivia-loader": LocalJSX.TriviaLoader & JSXBase.HTMLAttributes<HTMLTriviaLoaderElement>;
        }
    }
}
